### ISSUE TITLE
Fix bug with DataLoader metadata

### ISSUE THREAD

**Issue by aribrill** [bryankim96/ctalearn#32]
The following code fails with a KeyError:

```
>>> from ctalearn.data_loading import HDF5DataLoader
>>> data_loader = HDF5DataLoader(['/home/shevek/datasets/sample_prototype/gamma_20deg_0deg_srun4-100___cta-prod3_desert-2150m-Paranal-HB9_cone10.h5', '/home/shevek/datasets/sample_prototype/proton_20deg_0deg_srun1-10___cta-prod3_desert-2150m-Paranal-HB9.h5'])
>>> data_loader.get_metadata()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shevek/brill/ctalearn/ctalearn/data_loading.py", line 312, in get_metadata
    metadata['total_aux_params'] += metadata['num_additional_aux_params']
KeyError: 'num_additional_aux_params'
```

**Comment by bryankim96** [comment]
Fixed in f20f19ca0106b79324e7bada4772669c6086bffe.
